version: "3.5"
networks:
    model-renderer-network:
        name: model-renderer-network
services:
    nginx:
        container_name: model-renderer-nginx
        image: nginx:latest
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./app/dist:/var/www/model-renderer
        ports:
            - 8090:80
        networks:
            - model-renderer-network

    model-renderer:
        container_name: model-renderer
        image: node:latest
        volumes:
            - ./app:/app
        working_dir: /app
        expose:
            - "8080"
        command: "bash -c 'yarn && yarn run dev'"
        networks:
            - model-renderer-network
