version: "3.5"
networks:
    model-renderer-network:
        name: model-renderer-network
services:
    model-renderer:
        container_name: model-renderer
        image: node:latest
        volumes:
            - ./app:/app
        working_dir: /app
        ports:
            - "8080:8080"
        command: "bash -c 'yarn && yarn run dev-docker'"
        networks:
            - model-renderer-network
